Repository nf-core/tools, pull requests merged in 2018-08, with the labels that each got.

#113 lint fails more gracefully in travis doesn't have before_install
  nf_core/lint.py
Labels: linting

#110 Readme: Add docs about nf-core create
  README.md
Labels: documentation

#106 Use new manifest.nextflowVersion instead of params.minNextflowVersion
  docs/lint_errors.md
  nf_core/lint.py
  nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/environment.yml
  nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/main.nf
  nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/nextflow.config
  tests/lint_examples/failing_example/nextflow.config
  tests/lint_examples/minimal_working_example/environment.yml
  tests/lint_examples/minimal_working_example/nextflow.config
  tests/test_lint.py
Labels: linting, template

#118 Get rid of last pipeline linting warning by using newest MQC
  nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/environment.yml
Labels: linting

#117 Travis: Don't pull a docker image tag
  docs/lint_errors.md
  nf_core/lint.py
  nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/.travis.yml
  nf_core/release.py
  tests/lint_examples/minimal_working_example/.travis.yml
  tests/test_lint.py
Labels: linting

#115 Added manifest.name and manifest.pipelineVersion
  docs/lint_errors.md
  nf_core/lint.py
  nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/Dockerfile
  nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/Singularity
  nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/main.nf
  nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/nextflow.config
  nf_core/release.py
  tests/lint_examples/failing_example/nextflow.config
  tests/lint_examples/minimal_working_example/nextflow.config
  tests/test_lint.py
  tests/test_release.py
Labels: linting, template

#124 Docs redundancy
  nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/docs/configuration/adding_your_own.md
Labels: documentation

#134 Fixed config bug in singularity profile
  nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/nextflow.config
Labels: template

#135 Quote the new .travis.yaml tests
  .travis.yml
  nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/.travis.yml
  nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/docs/configuration/local.md
  nf_core/pipeline-template/{{cookiecutter.pipeline_slug}}/docs/usage.md
Labels: bug

#136 nf-core create: Refactor, add --outdir
  nf_core/create.py
  scripts/nf-core
Labels: command line tools

#138 Make --force work for nf-core create
  nf_core/create.py
Labels: command line tools

#142 Use config.get to avoid KeyErrors. Don't use --release for nf-core/tools
  nf_core/lint.py
  scripts/nf-core
Labels: command line tools

#151 Fix logic bug in automatic --release for linting
  scripts/nf-core
Labels: bug

#154 Documentation update
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/CONTRIBUTING.md
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/ISSUE_TEMPLATE/bug_report.md
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/ISSUE_TEMPLATE/feature_request.md
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#153 nf-core list: Fix release sorting and plurals
  README.md
  nf_core/list.py
Labels: bug

#66 Conda software licences
  README.md
  nf_core/licences.py
  nf_core/lint.py
  scripts/nf-core
  tests/test_lint.py
Labels: command line tools

#158 Adding functionality to nf-core list
  README.md
  nf_core/list.py
  scripts/nf-core
Labels: command line tools
