Repository nf-core/tools, pull requests merged in 2019-12, with the labels that each got.

#465 nf-core download - update docs on README file
  CHANGELOG.md
  README.md
Labels: documentation

#423 Sync refactor
  .travis.yml
  CHANGELOG.md
  README.md
  bin/blacklist.json
  bin/build_api_docs.sh
  bin/sync
  bin/syncutils/__init__.py
  bin/syncutils/template.py
  bin/syncutils/utils.py
  nf_core/sync.py
  scripts/nf-core
Labels: automation, command line tools

#475 Fix #85
  CHANGELOG.md
  docs/lint_errors.md
  nf_core/lint.py
  tests/lint_examples/minimalworkingexample/.travis.yml
  tests/lint_examples/minimalworkingexample/CHANGELOG.md
  tests/lint_examples/minimalworkingexample/Dockerfile
  tests/lint_examples/minimalworkingexample/LICENSE
  tests/lint_examples/minimalworkingexample/README.md
  tests/lint_examples/minimalworkingexample/conf/base.config
  tests/lint_examples/minimalworkingexample/docs/README.md
  tests/lint_examples/minimalworkingexample/docs/output.md
  tests/lint_examples/minimalworkingexample/docs/usage.md
  tests/lint_examples/minimalworkingexample/environment.yml
  tests/lint_examples/minimalworkingexample/main.nf
  tests/lint_examples/minimalworkingexample/nextflow.config
  tests/lint_examples/minimalworkingexample/tests/run_test.sh
  tests/test_bump_version.py
  tests/test_download.py
  tests/test_lint.py
Labels: linting
