Repository nf-core/tools, pull requests merged in 2019-09, with the labels that each got.

#368 [FIX] Missing r-markdown dependency
  CHANGELOG.md
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/environment.yml
Labels: automation, high-priority

#377 Add a dev branch automatically too
  CHANGELOG.md
  nf_core/create.py
Labels: Ready for Review

#378 Adding in more time
  CHANGELOG.md
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/base.config
Labels: Ready for Review

#381 Changes nf-core cache dir to user's home
  CHANGELOG.md
  nf_core/utils.py
Labels: Ready for Review

#394 Py3.7 compatibility
  .travis.yml
  CHANGELOG.md
  bin/syncutils/utils.py
  nf_core/download.py
  nf_core/launch.py
  nf_core/list.py
  nf_core/utils.py
  tests/test_list.py
Labels: command line tools
