Repository nf-core/tools, pull requests merged in 2020-02, with the labels that each got.

#515 Fix GitHub actions linting problems
  CHANGELOG.md
  docs/lint_errors.md
  nf_core/lint.py
  tests/lint_examples/minimalworkingexample/.github/workflows/branch.yml
Labels: linting

#517 Linting: check for 'dev' in pipeline version
  CHANGELOG.md
  docs/lint_errors.md
  nf_core/lint.py
  tests/lint_examples/failing_example/nextflow.config
  tests/test_lint.py
Labels: linting

#523 Split up GH actions, add PyPI deploy workflow
  .github/workflows/code-tests.yml
  .github/workflows/create-lint-wf.yml
  .github/workflows/deploy-pypi.yml
  .github/workflows/markdown-lint.yml
  .github/workflows/tools-api-docs.yml
  CHANGELOG.md
  bin/build_api_docs.sh
Labels: automation, pipeline-testing

#526 More GitHub Actions tweaks
  .github/workflows/create-lint-wf.yml
  .github/workflows/tools-api-docs.yml
  CHANGELOG.md
Labels: automation

#534 add YAML linting
  CHANGELOG.md
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/linting.yml
Labels: automation, linting

#536 It's not a preprint
  CHANGELOG.md
  README.md
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md
Labels: template

#543 Added release checklist for tools
  .github/RELEASE_CHECKLIST.md
  CHANGELOG.md
Labels: documentation
