Repository nf-core/tools, pull requests merged in 2020-07, with the labels that each got.

#661 Launch bugfix
  nf_core/launch.py
  tests/test_launch.py
Labels: command line tools

#663 add TODO check_samplesheet
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/bin/check_samplesheet.py
Labels: WIP

#615 Module import
  nf_core/__main__.py
  nf_core/modules.py
  tests/test_modules.py
Labels: WIP

#684 Do not use pre-release PyInquirer
  .github/CONTRIBUTING.md
  .github/workflows/pytest.yml
  README.md
  nf_core/launch.py
  nf_core/schema.py
  requirements-dev.txt
  setup.py
  tests/test_launch.py
Labels: command line tools

#692 Use new Rich syntax for markup logs.
  nf_core/__main__.py
  nf_core/bump_version.py
  nf_core/create.py
  nf_core/launch.py
  nf_core/lint.py
  nf_core/schema.py
  nf_core/sync.py
  setup.py
Labels: command line tools

#697 Dockerhub ci actions
  .gitignore
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/ci.yml
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/push_dockerhub.yml
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.gitignore
Labels: template

#716 Sync matrix
  .github/workflows/branch.yml
  .github/workflows/sync.yml
  CHANGELOG.md
  nf_core/__main__.py
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/CONTRIBUTING.md
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/branch.yml
  nf_core/sync.py
  tests/test_sync.py
Labels: high-priority
