Repository nf-core/tools, pull requests merged in 2021-04, with the labels that each got.

#983 update module commands with new format
  CHANGELOG.md
  nf_core/module-template/tests/test.yml
  nf_core/modules/create.py
  nf_core/modules/lint.py
  nf_core/modules/test_yml_builder.py
Labels: ready-for-review

#997 fixed template for "modules create"
  nf_core/module-template/tests/test.yml
Labels: DSL2

#999 FIx linting for the addition of publish_by_meta to the module template
  CHANGELOG.md
  nf_core/module-template/software/main.nf
  nf_core/modules/lint.py
  tests/test_modules.py
Labels: DSL2, high-priority, linting

#1014 Write docs for running nf-core tools docker image
  CHANGELOG.md
  README.md
Labels: command line tools, documentation

#1023 Fix mismatch === chars and colours in `checkHostname()` function
  nf_core/pipeline-template/main.nf
Labels: template

#1044 Functions nf comparison
  CHANGELOG.md
  nf_core/modules/lint.py
  tests/test_modules.py
Labels: DSL2
