Repository nf-core/tools, pull requests merged in 2021-03, with the labels that each got.

#867 Simplify charliecloud profile
  nf_core/bump_version.py
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/charliecloud.config
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config
  tests/test_bump_version.py
Labels: Ready for Review, template

#833 Add module test-yml generation tool
  CHANGELOG.md
  nf_core/__main__.py
  nf_core/modules.py
  tests/test_modules.py
Labels: DSL2, command line tools, ready-for-review

#871 Fix bug in unexpected param log with false values.
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/lib/NfcoreSchema.groovy
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config
Labels: ready-for-review, template

#873 Make --help output look nicer
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/lib/NfcoreSchema.groovy
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/main.nf
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow_schema.json
Labels: ready-for-review, template

#869 nf-core modules create
  CHANGELOG.md
  nf_core/__main__.py
  nf_core/licences.py
  nf_core/lint/__init__.py
  nf_core/lint/conda_env_yaml.py
  nf_core/module-template/cookiecutter.json
  nf_core/module-template/{{cookiecutter.tool_name}}/software/functions.nf
  nf_core/module-template/{{cookiecutter.tool_name}}/software/main.nf
  nf_core/module-template/{{cookiecutter.tool_name}}/software/meta.yml
  nf_core/module-template/{{cookiecutter.tool_name}}/tests/main.nf
  nf_core/module-template/{{cookiecutter.tool_name}}/tests/test.yml
  nf_core/module-template/{{cookiecutter.tool_name}}/{{cookiecutter.tool_name}}.nf
  nf_core/modules/__init__.py
  nf_core/modules/create.py
  nf_core/modules/pipeline_modules.py
  nf_core/modules/test_yml_builder.py
  nf_core/utils.py
  pyproject.toml
  setup.py
  tests/test_modules.py
Labels: DSL2, WIP, command line tools

#876 Create: extra stuff
  nf_core/licences.py
  nf_core/module-template/cookiecutter.json
  nf_core/module-template/{{cookiecutter.tool_name}}/software/main.nf
  nf_core/module-template/{{cookiecutter.tool_name}}/software/meta.yml
  nf_core/module-template/{{cookiecutter.tool_name}}/{{cookiecutter.tool_name}}.nf
  nf_core/modules/create.py
  nf_core/utils.py
  tests/test_licenses.py
Labels: DSL2, command line tools

#878 Remove nf-core modules check
  nf_core/__main__.py
  nf_core/launch.py
  nf_core/list.py
  nf_core/module-template/cookiecutter.json
  nf_core/module-template/software/functions.nf
  nf_core/module-template/software/main.nf
  nf_core/module-template/software/meta.yml
  nf_core/module-template/tests/main.nf
  nf_core/module-template/tests/test.yml
  nf_core/module-template/{{cookiecutter.tool_name}}/tests/main.nf
  nf_core/module-template/{{cookiecutter.tool_name}}/tests/test.yml
  nf_core/modules/create.py
  nf_core/modules/pipeline_modules.py
  nf_core/modules/test_yml_builder.py
  nf_core/utils.py
  tests/test_modules.py
Labels: DSL2, command line tools, ready-for-review

#894 Modules create - fuzzy finder for process label
  nf_core/modules/create.py
Labels: DSL2, command line tools, ready-for-review

#842 Adding `nf-core modules lint` command
  CHANGELOG.md
  README.md
  nf_core/__main__.py
  nf_core/modules/__init__.py
  nf_core/modules/lint.py
  nf_core/modules/pipeline_modules.py
  tests/test_modules.py
Labels: DSL2, linting, ready-for-review

#902 Bump version to 1.13
  .github/markdownlint.yml
  CHANGELOG.md
  README.md
  nf_core/create.py
  nf_core/lint/__init__.py
  nf_core/lint/merge_markers.py
  nf_core/lint/pipeline_todos.py
  nf_core/lint/template_strings.py
  nf_core/modules/lint.py
  nf_core/modules/pipeline_modules.py
  setup.py
  tests/lint/merge_markers.py
Labels: ready-for-review

#915 Fix lint md
  CHANGELOG.md
  nf_core/lint/__init__.py
  nf_core/pipeline-template/.github/workflows/branch.yml
  setup.py
Labels: high-priority

#930 fix bug for updated messages
  nf_core/modules/lint.py
  tests/test_modules.py
Labels: DSL2, bug, linting

#936 Fixing bugs in nf-core create
  nf_core/create.py
Labels: ready-for-review

#972 fix conda and podman profile strictness
  CHANGELOG.md
  nf_core/pipeline-template/nextflow.config
Labels: bug, template

#981 Add overwrite=true to trace reports etc for test configs
  CHANGELOG.md
  nf_core/pipeline-template/nextflow.config
Labels: WIP, ready-for-review

#979 Rewrote schema summary output function.
  CHANGELOG.md
  nf_core/pipeline-template/lib/NfcoreSchema.groovy
Labels: ready-for-review

#978 Sync: Try to fix the GitHub abuse mechanism coping code
  CHANGELOG.md
  nf_core/sync.py
Labels: ready-for-review
