Repository nf-core/tools, pull requests merged in 2021-06, with the labels that each got.

#1108 Revert recieved typo fix.
  nf_core/launch.py
  nf_core/schema.py
  tests/test_launch.py
  tests/test_schema.py
Labels: high-priority

#1116 Update modules install to support version control
  .github/workflows/create-lint-wf.yml
  CHANGELOG.md
  nf_core/__main__.py
  nf_core/modules/module_utils.py
  nf_core/modules/modules_repo.py
  nf_core/modules/pipeline_modules.py
  tests/test_modules.py
Labels: DSL2

#1121 Module lint refactor
  nf_core/__main__.py
  nf_core/modules/lint.py
  nf_core/modules/lint/__init__.py
  nf_core/modules/lint/functions_nf.py
  nf_core/modules/lint/main_nf.py
  nf_core/modules/lint/meta_yml.py
  nf_core/modules/lint/module_changes.py
  nf_core/modules/lint/module_tests.py
  nf_core/modules/lint/module_todos.py
  nf_core/modules/nfcore_module.py
Labels: DSL2, linting

#1125 Update modules lint
  CHANGELOG.md
  nf_core/lint/files_exist.py
  nf_core/modules/lint/__init__.py
  nf_core/modules/lint/main_nf.py
  nf_core/modules/lint/meta_yml.py
  nf_core/modules/lint/module_changes.py
  nf_core/modules/lint/module_tests.py
  nf_core/modules/lint/module_version.py
  nf_core/modules/modules_command.py
  nf_core/modules/nfcore_module.py
  nf_core/pipeline-template/modules.json
  tests/test_modules.py
Labels: linting

#1131 Add `nf-core modules bump-versions`
  CHANGELOG.md
  nf_core/__main__.py
  nf_core/modules/__init__.py
  nf_core/modules/bump_versions.py
  nf_core/modules/module_utils.py
  nf_core/utils.py
  tests/test_modules.py
Labels: DSL2

#1138 List - message if no results, suggest similar but different command
  nf_core/list.py
Labels: command line tools
