Repository nf-core/tools, pull requests merged in 2021-02, with the labels that each got.

#826 add Shifter + Charliecloud profiles
  CHANGELOG.md
  nf_core/bump_version.py
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/ISSUE_TEMPLATE/bug_report.md
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/README.md
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/conf/charliecloud.config
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/docs/usage.md
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/nextflow.config
  tests/test_bump_version.py
Labels: Ready for Review, template

#832 Download: Get DSL2 singularity containers
  CHANGELOG.md
  README.md
  nf_core/__main__.py
  nf_core/download.py
  nf_core/utils.py
  tests/test_download.py
Labels: DSL2, Ready for Review, command line tools, high-priority

#846 Lint: new files_unchanged test to check that files are not modified from the template
  CHANGELOG.md
  README.md
  docs/api/_src/lint_tests/actions_branch_protection.rst
  docs/api/_src/lint_tests/actions_lint.rst
  docs/api/_src/lint_tests/actions_schema_validation.rst
  docs/api/_src/lint_tests/files_unchanged.rst
  docs/api/_src/lint_tests/licence.rst
  nf_core/__main__.py
  nf_core/lint/__init__.py
  nf_core/lint/actions_branch_protection.py
  nf_core/lint/actions_lint.py
  nf_core/lint/conda_env_yaml.py
  nf_core/lint/files_exist.py
  nf_core/lint/files_unchanged.py
  nf_core/lint/licence.py
  nf_core/list.py
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/awsfulltest.yml
  nf_core/pipeline-template/{{cookiecutter.name_noslash}}/.github/workflows/awstest.yml
  nf_core/utils.py
  tests/lint/actions_branch_protection.py
  tests/lint/licence.py
  tests/test_lint.py
Labels: Ready for Review

#821 Sync improvement addressing #787
  CHANGELOG.md
  nf_core/sync.py
  tests/test_sync.py
Labels: Ready for Review, automation
