Repository nf-core/tools, pull requests merged in 2021-12, with the labels that each got.

#1347 Replaces suffix with completely customisable prefix variable
  nf_core/module-template/modules/main.nf
  nf_core/modules/lint/main_nf.py
  nf_core/pipeline-template/conf/modules.config
  nf_core/pipeline-template/modules.json
  nf_core/pipeline-template/modules/nf-core/modules/fastqc/main.nf
Labels: WIP

#1106 Stricter schema linting
  CHANGELOG.md
  nf_core/lint/schema_params.py
  nf_core/pipeline-template/lib/NfcoreSchema.groovy
  nf_core/schema.py
  nf_core/utils.py
Labels: ready-for-review

#1349 Update template with some DSL2 v2.0 bits detected during fetchngs ver 1.5 release
  CHANGELOG.md
  nf_core/pipeline-template/.github/CONTRIBUTING.md
  nf_core/pipeline-template/.github/workflows/awsfulltest.yml
  nf_core/pipeline-template/.github/workflows/awstest.yml
Labels: DSL2 v2.0

#1292 Fix setup
  MANIFEST.in
  pyproject.toml
  setup.py
Labels: ready-for-review

#1316 Cleaning up temporary files after test
  CHANGELOG.md
  nf_core/lint/files_unchanged.py
  tests/__init__.py
  tests/modules/create_test_yml.py
  tests/modules/install.py
  tests/test_bump_version.py
  tests/test_create.py
  tests/test_download.py
  tests/test_launch.py
  tests/test_lint.py
  tests/test_modules.py
  tests/test_schema.py
  tests/test_sync.py
  tests/test_utils.py
  tests/utils.py
Labels: ready-for-review
