Repository nf-core/tools, pull requests merged in 2022-10, with the labels that each got.

#1864 Jinja whitespace
  nf_core/module-template/tests/test.yml
Labels: low-priority

#1874 Tag the correct gitpod docker image name
  .github/workflows/push_dockerhub_release.yml
  CHANGELOG.md
Labels: automation

#1938 Autocanceling previous tests when pushing changes
  nf_core/pipeline-template/.github/workflows/ci.yml
Labels: enhancement, infrastructure
