Repository nf-core/tools, pull requests merged in 2024-02, with the labels that each got.

#2727 Pipeline template: Fix download test CI
  CHANGELOG.md
  nf_core/pipeline-template/.github/workflows/download_pipeline.yml
Labels: bug

#2757 Template: Fix GitHub Actions CI and Linting badges links
  CHANGELOG.md
  nf_core/pipeline-template/README.md
Labels: linting

#2768 nf-core download: Create container image symlinks so images are still found, even if registry config diverges.
  .github/workflows/pytest.yml
  CHANGELOG.md
  nf_core/download.py
  tests/test_download.py
Labels: high-priority
